// Pure renderers: data/camera-moves.json -> CSV and the README reference table.
// scripts/build.js writes the output; test/dataset.test.js checks it is in sync.

export const CATEGORIES = [
  'Pan/Tilt',
  'Zoom/Lens',
  'Dolly/Track',
  'Physical Moves',
  'Human Camera',
  'Drone/Crane',
  'Specials',
];

export const CSV_COLUMNS = [
  'id',
  'name',
  'category',
  'description',
  'prompt',
  'prompt_template',
  'best_for',
  'tips',
  'negatives',
  'recommended_duration_min_s',
  'recommended_duration_max_s',
  'dramatic',
  'example_clip_url',
  'example_clip_webm_url',
  'poster_url',
  'example_clip_duration_s',
  'example_clip_width',
  'example_clip_height',
  'tutorial_url',
];

/** Separator used to flatten the `tips` and `negatives` arrays into one CSV cell. */
export const LIST_SEPARATOR = ' | ';

function csvCell(value) {
  const s = Array.isArray(value) ? value.join(LIST_SEPARATOR) : String(value);
  return /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function toCsv(records) {
  const lines = [CSV_COLUMNS.join(',')];
  for (const r of records) lines.push(CSV_COLUMNS.map((c) => csvCell(r[c])).join(','));
  return lines.join('\n') + '\n';
}

export const README_START = '<!-- camera-moves:start (generated by scripts/build.js, do not edit by hand) -->';
export const README_END = '<!-- camera-moves:end -->';

function readmeLink(record) {
  return record.tutorial_url.replace('utm_content=dataset', 'utm_content=readme-table');
}

function mdEscape(s) {
  return s.replace(/\|/g, '\\|').replace(/</g, '&lt;');
}

export function slugifyCategory(category) {
  // Mirrors GitHub's heading anchors: drop punctuation, spaces become hyphens.
  return category.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/ /g, '-');
}

export function readmeTable(records) {
  const out = [];
  for (const category of CATEGORIES) {
    const rows = records.filter((r) => r.category === category);
    if (!rows.length) continue;
    out.push(`### ${category}`, '');
    out.push('| Example | Move | Recipe | Length |');
    out.push('|---|---|---|---|');
    for (const r of rows) {
      const link = readmeLink(r);
      const img = `<a href="${link}"><img src="${r.poster_url}" width="200" alt="${r.name} camera movement example frame"></a>`;
      const move = `**[${mdEscape(r.name)}](${link})**<br><sub>${mdEscape(r.description)}</sub>`;
      const length = `${r.recommended_duration_min_s}–${r.recommended_duration_max_s}s`;
      out.push(`| ${img} | ${move} | ${mdEscape(r.prompt)} | ${length} |`);
    }
    out.push('');
  }
  return out.join('\n').trimEnd();
}

export function categoryIndex(records) {
  return CATEGORIES.map((c) => {
    const n = records.filter((r) => r.category === c).length;
    return `[${c}](#${slugifyCategory(c)}) (${n})`;
  }).join(' · ');
}

export function injectReadme(readme, records) {
  const start = readme.indexOf(README_START);
  const end = readme.indexOf(README_END);
  if (start < 0 || end < start) throw new Error('README is missing the camera-moves markers');
  const body = `${categoryIndex(records)}\n\n${readmeTable(records)}`;
  return `${readme.slice(0, start + README_START.length)}\n${body}\n${readme.slice(end)}`;
}
